version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8888
    volumes:
      - ./app/:/usr/src/app/
      - ./app/:/usr/src/app/app/static/
    ports:
      - 8888:8888
    networks:
      - backend
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    env_file: .env
    networks:
      - backend
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  logs:

networks:
  backend:
    driver: bridge